### PR TITLE
Added Cake Commands

### PR DESCRIPTION
**Pull request by gep13**

### CODE REVIEW

**Comment by gep13** [comment]
@devlead @patriksvensson...

What do you guys think of the following:

image

**Comment by patriksvensson** [comment]
@gep13 I think it's frikkin' awesome! :smile:

**Comment by patriksvensson** [comment]
@gep13 Can we add a submenu like `Add bootstrapper` > `Bash` | `Windows` as well?

**Comment by gep13** [comment]
Ooo, yes, that should be possible, yes.  A great idea!

**Comment by devlead** [comment]
Nice @gep13 👍

**Comment by gep13** [comment]
@patriksvensson what do you think about this?

image

**Comment by devlead** [comment]
It's an improvement 👍

**Comment by gep13** [comment]
Closing this in favour of https://github.com/agc93/Cake.VisualStudio

**Pull request closed without merging**
