### PR TITLE
Add Custom Icon File for Cake

### PR DESCRIPTION
**Pull request by gep13**
Relates to #3

### CODE REVIEW

**Comment by gep13** [comment]
@hmemcpy what are your thoughts on this?  I "think" I have done everything listed here:  https://github.com/Microsoft/VSProjectSystem/blob/master/doc/scenario/provide_custom_icons_for_the_project_or_item_type.md, but the `ApplyModifications` method in the ProjectTreeModifier is never called.  Any ideas? Thanks!

**Comment by gep13** [comment]
@adrianvmsft @AArnott I have tried to follow the instructions listed here:

https://github.com/Microsoft/VSProjectSystem/blob/master/doc/scenario/provide_custom_icons_for_the_project_or_item_type.md

To add the "default" custom icon to .cake files within my Visual Studio Extension, but it doesn't seem to be working.  I believe I have followed all the steps that were listed, but I think I must be missing something.

Any chance one of you could take a look, and help me out?  Thanks!

**Comment by AArnott** [comment]
I'm no longer on the project team, and @adrianvmsft is OOF. @jviau may be able to help you.

**Comment by gep13** [comment]
@AArnott thank you for getting back to me :+1:

**Comment by adrianvmsft** [comment]
@gep13 I am not familiar with cake-vs, is it based on the Project System Extensibility (aka CPS)? (I took a quick look at the sources, but didn't find any projects referencing Microsoft.VisualStudio.ProjectSystem.*.dll)

I would recommend trying first one of the existing icons (e.g. the JavaScript icon) to avoid some of the complexity around image manifest files. Once you get that part working, you can start looking at consuming your own icon.

**Comment by gep13** [comment]
@adrianvmsft In all honesty, I have no idea :smile: 

This is my first Visual Studio extension.  I have been trying to piece this together from various samples/examples that I have been seeing on the web.  How would I know if I was using a CPS based extension?  And is there good reason to do this strategy compared to another way of doing it?

**Comment by adrianvmsft** [comment]
Ok, let's step back for a second.
First of all I think you should decide whether you need a custom project type. Think of project type as an extension that orchestrates all the components that are involved (debuggers, language services, build, deployment, handles manipulations of the project file, etc). You can find more details here: https://msdn.microsoft.com/en-us/library/cc512961.aspx
https://msdn.microsoft.com/en-us/library/bb165083.aspx
You may be able to flavor an existing project type (e.g. the standard C# project) to achieve that instead of implementing your own project type, however, I am not very familiar with that process.

If you decide that you need a new project type, there are 2 ways to create them:
- using MPF - described in the MSDN article; the problem such implementations typically need large amounts of code (tens of thousands of lines of code) that become problematic to maintain
- using Project System Extensibility (recommended) that creates a CPS based project. Project system extensibility is a Visual Studio extension that adds a few templates, that allow you to easily create a custom project type.
https://github.com/Microsoft/VSProjectSystem/blob/master/doc/overview/intro.md

Project System Extensibility offers a template that you can conveniently use and get started in less than 5 minutes:
https://github.com/Microsoft/VSProjectSystem/blob/master/doc/overview/define_a_new_project_type.md
This will create a custom project type similar to the C# console application. After that you can follow these steps to add a custom item type to the project:
https://github.com/Microsoft/VSProjectSystem/blob/master/doc/overview/define_a_new_project_type.md

Hope this helps,
Adrian

**Comment by hmemcpy** [comment]
I think at this point creating an entire project system is a bit overkill, as we probably want to support a simple File -> Open File scenario, without creating additional .cakeproj files :)
In my opinion, if we can't find a good way to register a custom icon in VS, there's always a possibility to associate .cake files with an icon [using Windows Explorer shell](https://msdn.microsoft.com/en-us/library/windows/desktop/hh127427.aspx)...

**Comment by gep13** [comment]
Closing this in favour of this: https://github.com/agc93/Cake.VisualStudio

**Pull request closed without merging**
